config/routes.rb
Rodnetshowyou::Application.routes.draw do
  get "static_pages/about"
  resources :shows

  resources :bands

  root 'shows#index'

  get '/about' => 'static_pages#about'

  get '/bands/:id/shows' => 'bands#all_shows', as: :all_shows
  resources :bands, only: [:index]

end

app/models/band.rb
class Band < ActiveRecord::Base
	has_many :shows
	validates :name, :category, presence: true
end

app/models/show.rb
class Show < ActiveRecord::Base
	belongs_to :band

	validates :band_id, :local, :date, :description, presence: true
	validates :local, length: { maximum: 200 }
	validates :description, length: { maximum: 400 }
	validate :date_is_valid_datetime

	scope :band_id, -> (band_id) { where band_id: band_id }
  scope :local, -> (local) { where("local like ?", "%#{local}%")}

  def date_is_valid_datetime
  	if (date)
  	if date < Date.today
	    errors.add(:date, "Seu show não pode ocorrer anterior a #{Date.today.strftime("%d/%m/%Y")}")
		  end
	  end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :set_band, only: [:show, :edit, :update, :destroy]

  # GET /bands
  def index
    @bands = Band.all
  end

  # GET /bands/1
  def show
  end

  # GET /bands/new
  def new
    @band = Band.new
  end

  # GET /bands/1/edit
  def edit
  end

  # POST /bands
  def create
    @band = Band.new(band_params)

    if @band.save
      redirect_to @band, notice: 'Banda criada com sucesso!'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /bands/1
  def update
    if @band.update(band_params)
      redirect_to @band, notice: 'Band was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /bands/1
  def destroy
    @band.destroy
    redirect_to bands_url, notice: 'Band was successfully destroyed.'
  end

  def all_shows
    @band = Band.find(params[:id])
    @shows = @band.shows
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_band
      @band = Band.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def band_params
      params.require(:band).permit(:name, :category)
    end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  before_action :set_show, only: [:show, :edit, :update, :destroy]

  # GET /shows
  def index
    
    @bands = Band.all.order(:name)
    
    if params[:s] == "all"
      @shows = Show.all.order(:date)
    else
      @shows = Show.where(:date => Time.zone.now..(Time.zone.now + 30.days)).order(:date)
    end

    filtering_params(params).each do |key, value|
      @shows = @shows.public_send(key, value) if value.present?
    end
  end

  # GET /shows/1
  def show
  end

  # GET /shows/new
  def new
    @show = Show.new
    @bands = Band.all.order(:name)
  end

  # GET /shows/1/edit
  def edit
  end

  # POST /shows
  def create
    @bands = Band.all.order(:name)
    @show = Show.new(show_params)

    if @show.save
      redirect_to @show, notice: 'Show criado com sucesso!'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /shows/1
  def update
    if @show.update(show_params)
      redirect_to @show, notice: 'Show was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /shows/1
  def destroy
    @show.destroy
    redirect_to shows_url, notice: 'Show was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_show
      @show = Show.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def show_params
      params.require(:show).permit(:band_id, :local, :date, :description)
    end
    def filtering_params(params)
      params.slice(:local, :band_id)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title = '')
    base_title = "Rod's NetShow.you"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/bands/_form.html.haml
= form_for @band do |f|
  - if @band.errors.any?
    #error_explanation
      %h2= "#{pluralize(@band.errors.count, "erro")} impediu a criação desta banda:"
      %ul
        - @band.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label "Nome"
    = f.text_field :name
  .field
    = f.label "Categoria"
    = f.text_field :category
  .actions
    = f.submit 'Salvar'

app/views/bands/all_shows.html.haml
%h1 Shows de #{@band.name}

%table.table.table-striped
  %tr
    %th Banda
    %th Local
    %th Data
    //%th Description
    %th
    //%th
    //%th

  - @shows.each do |show|
    %tr
      %td= link_to show.band.name, band_path(show.band_id)
      %td= show.local
      %td= show.date.strftime("%d/%m/%Y às %H:%M")
      //%td= show.description
      %td= link_to 'Detalhes', show
      //%td= link_to 'Edit', edit_show_path(show)
      //%td= link_to 'Destroy', show, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

app/views/bands/edit.html.haml
%h1 Editing band

= render 'form'

= link_to 'Show', @band
\|
= link_to 'Back', bands_path

app/views/bands/index.html.haml
%h1 Bandas

%table.table.table-striped
  %tr
    %th Nome
    %th Categoria
    %th
    //%th
    //%th

  - @bands.each do |band|
    %tr
      %td= band.name
      %td= band.category
      %td= link_to 'Todos os Shows', all_shows_path(band)
      //%td= link_to 'Edit', edit_band_path(band)
      //%td= link_to 'Destroy', band, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'Criar Banda', new_band_path, class: "btn btn-lg btn-primary"

app/views/bands/new.html.haml
%h1 Nova banda

= render 'form'

= link_to 'Back', bands_path

app/views/bands/show.html.haml
%p#notice= notice

%h1 
  = @band.name
%h2
  = @band.category

%h3
  = link_to "Ver todos os shows de #{@band.name}", all_shows_path(@band)

app/views/layouts/_footer.html.haml
%footer.footer
  %nav
    %ul
      %li= link_to "Sobre", about_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= full_title(yield(:title))
    = stylesheet_link_tag 'application', media: 'all', |
      'data-turbolinks-track' => true                  |
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header.navbar.navbar-fixed-top.navbar-inverse
      .container
        = link_to "Rod's NetShow.you", root_path, id: "logo"
        %nav
          %ul.nav.navbar-nav.navbar-right
            %li= link_to "Shows", shows_path
            %li= link_to "Bandas", bands_path
    .container
      = yield
      = render 'layouts/footer'

app/views/shows/_form.html.haml
= form_for @show do |f|
  - if @show.errors.any?
    #error_explanation
      %h2= "#{pluralize(@show.errors.count, "erro")} impediu a criação deste show:"
      %ul
        - @show.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label "Banda"
    = select("show", "band_id", @bands.collect {|b| [ b.name, b.id ] }, { include_blank: true })
  .field
    = f.label "Local"
    = f.text_field :local
  .field
    = f.label "Data"
    = f.text_field :date, as: :string, label: false, class: 'datetimepicker-control'
    :plain
      <script>initDatetimepicker();</script>
  .field
    = f.label "Descrição"
    = f.text_field :description
  .actions
    = f.submit 'Salvar'

app/views/shows/edit.html.haml
%h1 Editing show

= render 'form'

= link_to 'Show', @show
\|
= link_to 'Back', shows_path

app/views/shows/index.html.haml
%h1 Veja um show

%section#entry-content
  .navigate
    .change_view
      = link_to "Próximos 30 dias", shows_path
    .change_view
      = link_to "Todos", shows_path(s: "all")

  :javascript
    var loc = window.location.pathname + location.search;
    $('.navigate').find('div').each(function() {
      if ($(this).find('a').attr('href') == loc) {
        $(this).addClass('selected');
      }
    });

= form_tag("/shows", method: "get") do
  = label_tag(:band_id, "Banda:")
  = select_tag(:band_id, options_from_collection_for_select(@bands, "id", "name"), include_blank: true)
  = label_tag(:local, "Localização")
  = text_field_tag(:local)
  = hidden_field_tag('s', params[:s])
  = submit_tag("Pesquisa")

%table.table.table-striped
  %tr
    %th Banda
    %th Local
    %th Data
    //%th Description
    %th
    //%th
    //%th

  - @shows.each do |show|
    %tr
      %td= link_to show.band.name, band_path(show.band_id)
      %td= show.local
      %td= show.date.strftime("%d/%m/%Y às %H:%M")
      //%td= show.description
      %td= link_to 'Detalhes', show
      //%td= link_to 'Edit', edit_show_path(show)
      //%td= link_to 'Destroy', show, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'Criar Show', new_show_path, class: "btn btn-lg btn-primary"

app/views/shows/new.html.haml
%h1 O show vai começar<i>!</i>

= render 'form'

= link_to 'Back', shows_path

app/views/shows/show.html.haml
%p#notice= notice

%h1
  = "Show de #{@show.band.name}"

%p
  %b Banda:
  = link_to @show.band.name, band_path(@show.band_id)
%p
  %b Local:
  = @show.local
%p
  %b Data:
  = @show.date.strftime("%d/%m/%Y às %H:%M")
%p
  %b Descrição:
  = @show.description

//= link_to 'Edit', edit_show_path(@show)
//\|
= link_to 'Voltar', shows_path

app/views/static_pages/about.html.haml
%h1 Sobre
%p Este é um app desenvolvido em Ruby on Rails por Rodrigo Alves para aprovação da Netshow.me 
%a{:href => "https://gist.github.com/nicolaslazartekaqui/1f7309a0d32446f7515c"} Projeto